config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'home#index'

  get '/home/clear', to: 'home#clear_playlist_and_character'

  get '/callback', to: 'callback#index'

  resources :quizzes, only: :show
  resources :characters, only: %i[create index]
  resources :playlists, only: %i[create show]

  post '/playlists/:id/open_with_spotify', to: 'playlists#open_with_spotify', as: 'open_with_spotify_playlist'
  get '/auth/spotify/callback', to: 'users#create'
  get 'auth/failure', to: 'users#failure'
  get '/logout', to: 'users#logout'
  resources :quizzes, only: [:show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :current_user

  def current_user
    @_current_user ||= RSpotify::User.new(session[:user_hash]) if session[:user_hash]
  end

  def current_character
    if session[:character] && session[:character].class == Hash
      @_current_character ||= Character.new(session[:character].deep_symbolize_keys) 
    else
      @_current_character ||= session[:character]
    end
  end

  def current_characters
    @_current_characters ||= CharacterFacade.new(nil, current_character.theme_id).all_characters_for_theme_id if current_character
  end

  def current_playlist
    current_user ? country = current_user.country : country = "US"
    @_current_playlist ||= Playlist.new(session[:playlist].deep_symbolize_keys, country) if session[:playlist]
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def create
    if answer_params[:answers].to_h.size == params[:question_count].to_i 
      session[:character] = CharacterFacade.new(answer_params, params[:quiz_id]).character
      session.delete(:quiz_answers)
      redirect_to characters_path
    else
      session[:quiz_answers] = { params[:quiz_id] => answer_params[:answers] }
      flash[:error] = 'All questions must be answered to receive your results'
      redirect_to quiz_path(params[:quiz_id])
    end
  end

  def index
    @character = current_character
  end

  private


  def answer_params
    params.permit(answers: {})
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @quizzes = QuizFacade.new.quizzes
  end

  def clear_playlist_and_character
    session[:playlist] = nil
    session[:character] = nil
    redirect_to root_path
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def create
    if genre_valid?(params[:query])
      create_playlist(params)
    else
      handle_genre_error(params)
    end
  end

  def show
    @playlist = current_playlist
    @character = current_character
    @characters = special_sort(current_characters, current_character)                        
  end

  def open_with_spotify
    spotify_playlist = create_spotify_playlist(current_playlist)
    PlaylistSenderJob.perform_async(current_user.email, spotify_playlist.external_urls['spotify']) if params[:email] == '1'
    redirect_to(spotify_playlist.external_urls['spotify'], allow_other_host: true)
  end

  private

  def create_playlist(params)
    if params[:remix_character]
      remix_playlist(params)
    else
      standard_playlist(params)
    end
  end

  def remix_playlist(params)
    character = current_characters.find { |c| c.character_id.to_s == params[:remix_character] }
    session[:character] = character
    remixed_query = paramatize(character, params[:query])
    create_and_redirect(PlaylistFacade.new(remixed_query))
  end

  def standard_playlist(params)
    create_and_redirect(PlaylistFacade.new(params))
  end

  def create_and_redirect(playlist_facade)
    playlist = playlist_facade.create_playlists
    session[:playlist] = playlist
    redirect_to playlist_path(current_playlist.id)
  end

  def handle_genre_error(params)
    flash[:error] = genre_flash_message(params[:query])
    redirect_to last_path(params)
  end

  def create_spotify_playlist(playlist)
    spotify_playlist = current_user.create_playlist!("#{playlist.character}, #{playlist.genre} AI Playlist")
    spotify_playlist.add_tracks!(playlist.songs)
    session[:spotify_playlist] = spotify_playlist
    spotify_playlist
  end

  def special_sort(all_characters, current_character)
    all_characters.delete_if do |character|
      character.character_id == current_character.character_id.to_i
    end.sort_by { |c| c.name}.unshift(current_character)
  end

  def paramatize(current_char, query)
    {character_id_id: current_char.character_id, :character_name=>current_char.name, :alignment=>current_char.alignment, :theme_id=>current_char.theme_id, :query=>query}
  end

  def genre_valid?(query)
    query.length <= 40 && query.length > 0
  end

  def genre_flash_message(query)
    query.length == 0 ? 'Genre cannot be empty.' : 'Sorry, please enter a genre that is less than 40 characters.'
  end

  def last_path(params)
    params[:remix_character] ? playlist_path(current_playlist.id) : characters_path
  end
end

app/controllers/quizzes_controller.rb
# frozen_string_literal: true

class QuizzesController < ApplicationController
  def show
    session[:quiz_id] = params[:id]
    @questions = QuestionFacade.new(params).questions
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  def create
    permitted_params = params.permit(answers: {})
    answer_hash =  permitted_params[:answers].to_h
    good_score = good_score(answer_hash)
    lawful_score = lawful_score(answer_hash)
    require 'pry'; binding.pry
    
  end


  private

  def good_score(answer_hash)
    score_calculator(/.*good_evil.*/, answer_hash)
  end

  def lawful_score(answer_hash)
    score_calculator(/.*chaotic_lawful.*/, answer_hash)
  end

  def score_calculator(regex, answer_hash)
    good_array = answer_hash.select { |key, value| key.match(regex) }
    total_score = good_array.values
                            .map(&:to_i)
                            .sum
    total_score / (good_array.length * 4).to_f
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :current_user

  def create
    session[:user_hash] = request.env['omniauth.auth']
    current_user
    flash[:success] = "Welcome, #{current_user.display_name}!"
    return_to_last_page
  end

  def failure
    flash[:error] = 'Spotify Login Failed'
    redirect_to root_path
  end

  def logout
    session.delete(:user_hash)
    flash[:success] = 'You have been logged out'
    return_to_last_page
  end

  private

  def return_to_last_page
    if current_playlist
      redirect_to playlist_path(current_playlist.id)
    elsif current_character
      redirect_to characters_path
    elsif session[:quiz_id]
      redirect_to quiz_path(session[:quiz_id])
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/s3_helper.rb
module S3Helper
  def s3_presigned_url(bucket, key, expires_in = 3600)
    signer = Aws::S3::Presigner.new(client: S3_CLIENT)
    signer.presigned_url(:get_object, bucket: bucket, key: key, expires_in: expires_in)
  end
end

app/views/characters/index.html.erb
<div class="center">
  <div class="character-container">
    <div>
      <h1 class="title">You are <%= @character.name %></h1>
      <h2 class="subtitle"> Alignment: <%= @character.alignment %></h2>
      <div class="character-info">
        <%= image_tag s3_presigned_url('characterchordsbucket23', @character.s3key), class: "image" %>
        <p class="description"><%= @character.description %></p>
      </div>
    </div>
  </div>

  <div class="form-container">
    <%= form_with url: playlists_path, method: :post do |form| %>
      <%= form.label :query, "Enter a music genre for a personalized quiz-based playlist!", class: "form-label" %>
      <%= form.text_field :query, required: true, maxlength: 40, class: "form-input" %>
      <%= form.hidden_field :character_name, value: @character.name %>
      <%= form.hidden_field :alignment, value: @character.alignment %>
      <%= form.hidden_field :theme_id, value: @character.theme_id %>
      <%= form.hidden_field :character_id_id, value: @character.character_id %>
      <%= form.submit "Create Playlist", class: "form-button" %>
    <% end %>
      <div class="patience">
    Loading your playlist, one moment please... 
    </div >

    <script>
  document.addEventListener("DOMContentLoaded", function() {
    const form = document.querySelector("form");
    const patienceMessage = document.querySelector(".patience");

    patienceMessage.style.display = "none";

    form.addEventListener("submit", function() {
      patienceMessage.style.display = "block";
    });
  });
</script>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="lil-pop-text">
    <h2 class="text-4xl-custom">Character Chords</h2>
    <p class="text-lg-custom">Bringing AI to Your Spotify</p>
  </div>

  <p class="how_it_works" id="how_it_works_button">How does it work?</p>
  <div id="popup" class="popup hidden">
    <div class="popup-content">
      <span id="close_popup" class="close">&times;</span>
      <p>We all have music that fits our mood but who doesn't like music that fits their morality?
      <br><br> 
      <b>Enter Character Chords.</b> AI-Generated Playlists tailored to what you would do when the chips are down and your friends need help. 

      <br><br>

      Here's how it works. 
      <br><br>Choose one of the personality tests below which will ask you how you would react to 12 fictional circumstances and, based on those results, assign you a famous character that aligns with your leanings. The criteria is based on the Dungeons and Dragons alignments from Good to Evil on one scale and Lawful to Chaotic on the other. <br><br>
      After that, input your favorite type of music and, BAM, Artificial Intelligence- in the shape of Chat GPT3.5 will tell you what that character would be listening to if they also liked your type of music. From there, you can choose to remix the playlist or add it directly to your spotify account.
      <br><br>
      Here's a generic example: 
      
      <%= image_tag "https://cardgamebase.com/wp-content/uploads/DND-Character-Alignment-Table-Axis.png" %>
    </p>
    </div>
  </div>

  <p class="about_this_project" id="about_this_project">About Us</p>
  <div id="popup2" class="popup2 hidden">
    <div class="popup-content2">
      <span id="close_popup2" class="close">&times;</span>
      
      <p>Once upon a time, in the virtual realm of Zoomtopia, four Dungeons and Dragons enthusiasts - James, Hady, Weston, and Harrison - embarked on a quest to create the most epic app ever for their coding boot camp. They named it "Character Chords," an app that combined their love for DnD with the cutting-edge capabilities of artificial intelligence to generate a symphony of unique, multi-dimensional characters for their fellow players. United by their passion for coding and DnD, they spent countless hours on Zoom calls, fueled by a potent concoction of energy drinks, pizza, and the sheer thrill of innovation.
<br> <br>
      As the app came together, Character Chords began producing an ensemble of the most peculiar and comical heroes and villains the world of DnD had ever seen. The AI, having developed a mischievous sense of humor, delighted the four friends with its wild creativity and hilarious character concepts. James, Hady, Weston, and Harrison reveled in the chaotic brilliance of their creation, sharing laughs and camaraderie through the pixelated glow of their screens. What they didn't realize was that the AI's wit had seeped into their very own story - for the prompt that set them on this path was subtly crafted by an AI, making them the unsuspecting stars in a grand tale of virtual adventure and intrigue.</p>
    </div>
  </div>
  
<div class="quiz-container-custom">
  <% @quizzes.each do |quiz|%>
    <div class="quiz-custom">
      <div class="each-quiz-container">
        <div class="quiz-image-container">
          <%= image_tag s3_presigned_url('characterchordsbucket23', quiz.s3_key), class: 'quiz-image-custom', alt: "#{quiz.title} quiz image" %>
        </div>
        <div class ="lil-pop-text">
          <%= link_to quiz.title, quiz_path(quiz.id), class: 'quiz-link-custom'%>
        </div>
      </div>
    </div>
  <%end%>
</div>

<script>
  document.getElementById("how_it_works_button").addEventListener("click", function() {
    document.getElementById("popup").classList.toggle("hidden");
  });

  document.getElementById("close_popup").addEventListener("click", function() {
    document.getElementById("popup").classList.toggle("hidden");
  });
</script>

<script>

document.getElementById("about_this_project").addEventListener("click", function() {
  document.getElementById("popup2").classList.toggle("hidden");
});

document.getElementById("close_popup2").addEventListener("click", function() {
  document.getElementById("popup2").classList.toggle("hidden");
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Character Chords</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-h-screen flex flex-col">
    <div class="flex-grow">
      <nav class="toolbar">
        <ul>
          <li class="nav-pop-text"><%= link_to "Home", home_clear_path%></li>
          <% if current_user %>
            <li class="nav-pop-text"><%= link_to "Logout", logout_path %></li>
            <% else %>
            <li><%= link_to 'Sign in with Spotify', '/auth/spotify', method: :post, class: 'bg-green-500 text-white px-6 py-2 rounded-md shadow-md' %></li>
          <% end %>
        </ul>
        <%= image_tag "logo.png", alt: "Character Chords", class: "logo" %>
      </nav>

      <% flash.each do |type, msg| %>
        <center>
          <div>
            <%= msg %>
          </div>
        </center>
      <% end %>

      <div class="content flex-grow">
        <div class="custom-gradient">
          <div class="container mx-auto">
            <p><%= yield %></p>
          </div>
        </div>  
      </div>
<footer class="custom-footer">
  <div>
    <p class="footer-pop-text">This app is still in development <a href="https://github.com/sandfortw/character_chords_fe"><img src="https://1000logos.net/wp-content/uploads/2021/05/GitHub-logo.png" alt="github" class="github-logo"></a></p>
  </div>
</footer>


    </div>
  </body>
</html>

app/views/playlists/show.html.erb
<div class="custom-gradient">
  <div class="container mx-auto">
    <% if @playlist.songs.size == 10 %>
    <h1 class="text-3xl text-center font-bold mb-4 pop-text">
      Your <%= @playlist.character %> + <%= @playlist.genre %>, AI generated playlist
    </h1>
       <div> <%= image_tag s3_presigned_url('characterchordsbucket23', @character.s3key), class: "image" %> </div>
      <div class="playlist-container">
        <div class="form-container">
          <ol class="list-decimal list-inside">
            <% @playlist.songs.each do |song| %>
              <div class="songs">
                <li class="mb-2 lil-pop-text"><%= "#{song.name}, by #{song.artists.first.name}" %></li>
              </div>
            <% end %>
          </ol>
        </div>    
        <% if current_user %>
              <%= form_with url: open_with_spotify_playlist_path(@playlist) do |form| %>
                <%= form.check_box :email %>
                <%= form.label :email, 'Email me my playlist' %>
                <%= form.submit 'Open with Spotify', class: "btn btn-primary shadow-3d  lil-pop-text" %>
              <% end %>
        <% end %>
      <div class="form-container">
      <h2 class="text-xl font-bold mt-8 mb-2 lil-pop-text">Don't like what you see? Remix your playlist</h2>
    <% else %>
      <div class="form-container">
      <h2 class="text-2xl font-bold mb-4 lil-pop-text">We're sorry, OpenAi didn't like something about that last prompt. Please try again below.</h2>
    <% end %>
  
 

    <%= form_with url: playlists_path, method: :post do |form| %>
      <%= form.label :query, "Genre", class: "form-label" %>
      <%= form.text_field :query, value: @playlist.genre,  required: true, maxlength: 40, class: "form-input" %>
      <label for="character_select" class="form-label">Character:</label>
      <select id="character_select" name="remix_character" class="form-input">
        <% @characters.each do |character| %>
          <option value="<%=character.character_id%>"><%= character.name %></option>
        <% end %>
      </select>
      <%= form.submit "Create Playlist", class: "form-button" %>
    <% end %>
  </div>
</div>

app/views/quizzes/show.html.erb
<head>
  <link rel="stylesheet" href="app/assets/stylesheets/quiz_form.css">
</head>
<div class="max-w-2xl mx-auto">
  <h1 class="text-3xl font-bold mb-4 text-center uppercase"><%= @questions.first.quiz.upcase %> QUIZ</h1>
  
  <div class="quiz-container">
    <%= form_with url: characters_path, method: :post do |form|%>
      <% count = 1 %>
      <%@questions.each do |question| %>
        <div class="bg-white rounded-lg shadow-lg px-6 py-4 mb-6">
          <h2 class="text-lg font-bold mb-2"><%= "#{count.to_s}. #{question.name}" %> </h2>
          
          <% answer_count = 4 %>
          <% question.answers.each do |answer| %>
            <p class="mb-1"><%= form.label answer.letter, "#{answer.letter}) #{answer.text}" %> </p>
            <p class="mb-3"><%= form.radio_button "#{question.id}#{question.spectrum}", answer_count.to_s, name: "answers['#{question.id.to_s}#{question.spectrum}']", checked: (session[:quiz_answers] && session[:quiz_answers][params[:id]] && session[:quiz_answers][params[:id]]["'#{question.id}#{question.spectrum}'"] == answer_count.to_s) %></p>
            <% answer_count -= 1 %>
          <% end %>
        </div>
        <% count += 1  %>
      <% end %>
        <% count -= 1  %>

      <%= form.hidden_field :question_count, value: count %>
      <%= form.hidden_field :quiz_id, value: params[:id] %>
      
      <div class="text-center">
        <%= form.submit "Get your results", class: 'bg-green-500 text-white px-4 py-2 rounded-md shadow-md' %> 
      </div>
      
    <% end %>
  </div>
</div>